services:
  nest_app:
    build:
      context: .
      dockerfile: Dockerfile
    #image: orion_client
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./src:/app/src

    environment:   
      - CHOKIDAR_USEPOLLING=true

