services:
  nest_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: orion_client
    ports:
      - 3000:3000
    restart: always
    volumes:
      - .:/app
      - /app/node_modules